spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping-study
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver


file:
  dir: /Users/dongwook/Desktop/study/study/file/
